### ISSUE TITLE
내 리스트 페이지 안 영화 폴더 부분

### ISSUE THREAD

**Issue by Jacksieze** [Renoris/takealook#123]
내 리스트 페이지 안에 있는 영화 폴더에 리스트를 추가 후, 계정 안에 있는 선택된 내 취향 영화를 제거 시 폴더 안에 있던 해당 영화 리스트는 사라지고, 대표 이미지만 남아있는 현상이 있다. 
이를 복구 하려면 해당 영화를 메인 페이지에서 다시 픽 해야 된다.

**Comment by Renoris** [comment]
기존 로직: 영화 폴더 영화 선택모달에서 취향리스트 api를 불러와 이 취향리스트 중 내 영화 폴더에 있는 영화 id와 대조해 선택한것을 위로 안선택한것을 아래로 배치 => 선택하면 영화 폴더 아이템에 해당 영화 id 저장

문제점: 취향리스트를 불러와 그 기반으로 배치하기 때문에 영화 폴더에 저장된 영화 id가 있고 해당 영화썸네일을 불러오지만 취향리스트에서 해제 되었을 경우 영화 폴더 선택모달에서는 취향리스트 api를 불러오기 때문에 보이지 않음

해결 : 영화 폴더 선택 모달에서 취향리스트 api 기반 => 영화 폴더내 저장된 영화 기반 (백엔드에서 title과 썸네일을 추가로 불러옴)으로 변경
해당 api를 불러왔을때 전부 위로 올리고 취향리스트에서 불러온 것중 위에 선택되지 않은 것을 전부 아래로 배치 (위에서 선택된 것은 그대로 제거)
